services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    nodeVersion: 20.17.0  # Not necessary for Python apps, but this will depend on your stack
